import { getCatalogueProvenance } from "./sukl-client";
import { escapeEmailHtml as escape } from "./resend";
const contact = "petr.sovadina9@gmail.com";
function page(title: string, content: string, status = 200) {
  return new Response(`<!doctype html><html lang="cs"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · SÚKL MCP</title><style>body{font:17px/1.7 system-ui;color:#182b40;background:#f5f8fb;margin:0}main{max-width:740px;margin:40px auto;padding:30px;background:white;border-radius:16px}a{color:#155ca0}h1{line-height:1.3}nav{display:flex;gap:18px;flex-wrap:wrap}.draft{background:#fff1cc;padding:16px;border-radius:8px}</style><main><nav><a href="/chatgpt">Plugin</a><a href="/chatgpt/support">Podpora</a><a href="/privacy">Soukromí</a><a href="/terms">Podmínky</a></nav><h1>${escape(title)}</h1>${content}<p><small>Zdroj: <a href="https://opendata.sukl.gov.cz/">SÚKL</a>. <a href="https://opendata.sukl.gov.cz/?q=podminky-uziti-otevrenych-dat">Podmínky užití otevřených dat</a>. Licence MIT se vztahuje na zdrojový kód, nikoli automaticky na dokumenty třetích stran.</small></p><p><small>Nezávislý projekt Petra Sovadiny. Nejde o oficiální aplikaci SÚKL.</small></p></main></html>`, { status, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
}
export function pluginPage() {
  const source = getCatalogueProvenance();
  return page("České léky v konverzaci", `<p>SÚKL MCP pomáhá během konverzace najít české léčivé přípravky, rozlišit jejich balení a otevřít oficiální příbalové informace nebo souhrny údajů o přípravku.</p><ul><li>Vyhledání podle názvu, uvedené látky nebo kódu SÚKL.</li><li>Katalogový detail, klasifikace ATC a přehledné karty léčiv.</li><li>Odkazy na PIL/SPC na webu SÚKL.</li><li>Bez přihlášení, nákupů a placených tarifů.</li></ul><p>Platnost aktuálního katalogu: ${escape(source.source_as_of ?? "neověřena")} až ${escape(source.source_valid_until ?? "neověřena")}.</p><p>Plugin nezjišťuje skutečné zásoby lékáren, ceny či nárok na úhradu a neposkytuje osobní doporučení léčby. Do dotazů zadávejte názvy nebo veřejné kódy léčiv, nikoli osobní zdravotní údaje. Odkaz na PDF neznamená, že plugin přečetl jeho obsah.</p><p>Publikace do veřejného katalogu ChatGPT je připravována. Odkaz na instalaci se zde objeví po schválení a zveřejnění OpenAI.</p>`);
}
export function supportPage() {
  return page("Podpora", `<p>Provozovatel a vývojář: Petr Sovadina.</p><p>Nahlaste chybu na <a href="https://github.com/petrsovadina/SUKL-mcp/issues">GitHubu projektu</a> nebo napište na <a href="mailto:${contact}">${contact}</a>. Uveďte název nástroje, veřejný kód přípravku a popis problému. Neposílejte diagnózy ani jiné citlivé osobní údaje.</p><p>Pro opravu osobních údajů z webového formuláře či odvolání souhlasu použijte uvedený email. Podpora neslouží pro léčebné konzultace.</p>`);
}
export function privacyPage() {
  const retention = process.env.PRIVACY_HOST_LOG_RETENTION;
  const formsRetention = process.env.PRIVACY_FORM_RETENTION;
  const ready = process.env.PUBLICATION_POLICY_CONFIRMED === "true" && retention && formsRetention && process.env.PRIVACY_REDIS_PROVIDER;
  return page("Ochrana osobních údajů", `${ready ? "" : '<p class="draft">Návrh pro kontrolu provozovatelem. Zásady ještě nejsou schváleny k veřejnému vydání. Je nutné potvrdit skutečnou dobu uchování a nastavení hostingu.</p>'}<p>Provozovatel: Petr Sovadina, kontakt <a href="mailto:${contact}">${contact}</a>.</p><p>MCP rozhraní zpracuje pouze argumenty zvoleného nástroje: název/látku/kód přípravku, ATC a omezení počtu výsledků. Nevyžaduje účet ani přístup k historii chatu. Nezadávejte údaje o zdraví konkrétní osoby. Aplikace neukládá dotazy do databáze a widget nemá analytické sledování, externí skripty ani cookies. Technický omezovač požadavků zpracuje IP adresu pro omezení zneužití. Ve veřejném provozu ukládá pouze pseudonymní otisk IP a čítač požadavků do nakonfigurované Redis služby s dobou uchování nejvýše 60 sekund; původní IP adresu do této služby nepředává. Poskytovatel Redis služby: ${escape(process.env.PRIVACY_REDIS_PROVIDER || "NEPOTVRZEN – doplní provozovatel")}. Při lokálním testování používá pouze dočasnou paměť procesu.</p><p>Při hledání PIL/SPC odešle server veřejný kód přípravku službě prehledy.sukl.cz. Po otevření dokumentu navštěvujete web SÚKL s jeho vlastními zásadami. Obsah a argumenty nástroje současně zpracovává OpenAI podle vašich podmínek pro ChatGPT.</p><p>Hosting Vercel může zpracovávat technické provozní údaje včetně IP adres, času a adresy požadavku za účelem doručení služby, bezpečnosti a řešení chyb. Potvrzená doba uchování těchto údajů: ${escape(retention || "NEPOTVRZENA – doplní provozovatel podle nastavení projektu")}. Aplikace neloguje těla MCP požadavků. Webová analytika je ve výchozím nastavení vypnuta; její zapnutí vyžaduje aktualizaci těchto zásad.</p><p>Samostatné formuláře na původním webu nejsou potřebné pro plugin. Pokud je použijete, zpracují zadaný email, jméno, firmu, volitelný telefon či zprávu a čas přijetí souhlasu pro odpověď na požadavek nebo přihlášení k novinkám. Údaje mohou obdržet Notion (správa kontaktů) a Resend (doručení emailu), jsou-li tyto služby nakonfigurovány. Potvrzená doba uchování: ${escape(formsRetention || "NEPOTVRZENA – doplní provozovatel")}. Newsletter lze odvolat přes kontaktní email.</p><p>O přístup, opravu, odstranění či omezení zpracování požádejte přes kontaktní email. Právní základ konkrétního formuláře a provozních údajů, zpracovatelské smlouvy a případné předání mimo EHP musí provozovatel ověřit před potvrzením těchto zásad. Uplatnění práv vůči OpenAI či SÚKL se řídí zásadami příslušné služby.</p>`, ready ? 200 : 503);
}
export function termsPage() {
  const ready = process.env.PUBLICATION_POLICY_CONFIRMED === "true";
  return page("Podmínky používání", `${ready ? "" : '<p class="draft">Návrh podmínek. Provozovatel jej musí potvrdit před veřejným publikováním.</p>'}<p>SÚKL MCP je bezplatný informační katalog provozovaný Petrem Sovadinou. Používá veřejná data SÚKL, jejichž zdroj a platnost uvádí u výsledků. Zdrojový kód je dostupný pod licencí MIT; tato licence nenahrazuje podmínky použití zdrojových dat.</p><p>Informace mohou být neúplné nebo se změnit. Pro závazné informace o konkrétním přípravku otevřete aktuální oficiální PIL/SPC a poraďte se s lékařem či lékárníkem. Služba neurčuje léčbu, dávkování pro konkrétní osobu, zaměnitelnost, skutečné skladové zásoby nebo nárok na úhradu a neumožňuje nákup léčiv.</p><p>Používejte pouze údaje o přípravcích, nezadávejte osobní zdravotní údaje a nepokoušejte se obcházet technické limity či narušit službu. Provoz může být dočasně omezen nebo přerušen při údržbě a nedostupnosti zdrojů. Tím nejsou dotčena práva uživatele podle závazných právních předpisů.</p><p>Podpora: <a href="mailto:${contact}">${contact}</a>. Zásady zpracování údajů jsou na <a href="/privacy">stránce soukromí</a>.</p>`, ready ? 200 : 503);
}
