import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { zipSync, strToU8 } from "fflate";
const root = "plugins/sukl-medicines";
const base = new URL(process.env.PLUGIN_BASE_URL ?? "https://sukl-mcp.vercel.app");
if (base.protocol !== "https:" || base.username || base.password || base.pathname !== "/") throw new Error("PLUGIN_BASE_URL musí být kořen HTTPS domény bez přihlašovacích údajů.");
const files = {};
function walk(path) { for (const entry of readdirSync(path, { withFileTypes:true })) { const absolute = join(path,entry.name); if(entry.isDirectory()) walk(absolute); else files[relative(root,absolute)] = new Uint8Array(readFileSync(absolute)); } }
walk(root);
const manifest = JSON.parse(readFileSync(join(root,"plugin.json"),"utf8"));
const listing = manifest.extensions["com.openai"].interface;
manifest.homepage = new URL("/chatgpt",base).href;
for (const [key,path] of Object.entries({websiteURL:"/chatgpt",supportURL:"/chatgpt/support",privacyPolicyURL:"/privacy",termsOfServiceURL:"/terms"})) listing[key] = new URL(path,base).href;
if (process.env.PLUGIN_DEMO_URL) manifest.extensions["com.openai"].review.demo_recording_url = process.env.PLUGIN_DEMO_URL;
files["plugin.json"] = strToU8(JSON.stringify(manifest,null,2));
const mcp = JSON.parse(readFileSync(join(root,"mcp.json"),"utf8"));
mcp.mcpServers["sukl-catalogue"].url = new URL("/chatgpt/mcp",base).href;
files["mcp.json"] = strToU8(JSON.stringify(mcp,null,2));
files["LICENSE"] = new Uint8Array(readFileSync("LICENSE"));
mkdirSync("plugin-dist",{recursive:true});
writeFileSync("plugin-dist/sukl-medicines-1.0.0.zip",zipSync(files));
writeFileSync("plugin-dist/plugin.json",files["plugin.json"]);
writeFileSync("plugin-dist/mcp.json",files["mcp.json"]);
console.log("Vytvořen plugin-dist/sukl-medicines-1.0.0.zip. Před veřejným odesláním spusťte plugin:check -- --live.");
